[package]
name = "ley"
version = "0.0.2"
authors = ["AidoP <aidop@me.com>"]
edition = "2018"
description = "Parser and html renderer of Ley files"
repository = "https://github.com/AidoP/ley"
readme = "readme.md"
license = "MIT"

categories = ["parser-implementations"]
keywords = []